### ISSUE TITLE
ob_clean();

### ISSUE THREAD

**Issue by aiphee** [fusonic/spreadsheetexport#5]
I needed to call ob_clean(); before Download, othewise ODS was broken.

**Comment by mburtscher** [comment]
You should check if there is any output before calling the download method. It's likely that your application already printed some output.

**Comment by asmundstavdahl** [comment]
I recommend you make sure to never have any space before your opening `<?php` tags, as well as make sure that you never manually close your PHP code with `?>` tags; any whitespace before the opening tag or after the closing tag will write to the output buffer. This phenomenon lost me some hair.

With proper separation of PHP and HTML code, you should not need to use the closing `?>` tag, especially in files dedicated to class or function definitions.

**Comment by mburtscher** [comment]
Not an issue of this library but the application. As @asmundstavdahl states you should never send any output implicitely.

**Comment by aiphee** [comment]
Still, wouldn’t be better to make sure user did not send anything before to prevent pointless search of a problem?

I certainly did not sent anything deliberately, my framework did.

**Comment by mburtscher** [comment]
I'm sorry but I don't think that this is the job of the library. A `ob_clean()` would also solve the problem only in certain cases. If there is already output flushed, it might not solve the problem at all.
